name: MyFitnessPal Sync

on:
  workflow_dispatch: # Bouton manuel dans l'onglet Actions

jobs:
  run-sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Installer les dépendances Python
        run: |
          pip install playwright seleniumbase beautifulsoup4 lxml gspread google-auth
          # Installe le navigateur pour l'utilisateur courant
          python -m playwright install chromium

      - name: Installer les dépendances système (Fix Sudo)
        # On utilise "python -m" avec sudo pour éviter l'erreur "command not found"
        run: |
          sudo $(which python) -m playwright install-deps chromium

      - name: Exécuter le script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          MFP_EMAIL: ${{ secrets.MFP_EMAIL }}
          MFP_PASSWORD: ${{ secrets.MFP_PASSWORD }}
        run: python mfp_automation.py

      - name: Sauvegarder les captures d'écran (Debug)
        if: always() # Récupère les images même si le login échoue
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-debug
          path: screenshot_*.png
