name: MyFitnessPal Sync

on:
  workflow_dispatch:

jobs:
  run-sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 1. Installer Librairies Python
        run: pip install playwright seleniumbase beautifulsoup4 lxml gspread google-auth

      - name: 2. Installer Navigateur Chromium
        run: python -m playwright install chromium
        run: pip install gspread google-auth



      - name: 4. Exécuter le script MyFitnessPal
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          MFP_EMAIL: ${{ secrets.MFP_EMAIL }}
          MFP_PASSWORD: ${{ secrets.MFP_PASSWORD }}
        run: python mfp_automation.py

      - name: 5. Upload Screenshots si erreur
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-results
          path: |
            *.png
            *.log
